[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  DATABASE_URL = "postgresql://neondb_owner:npg_8VNd2zamvBZI@ep-wild-firefly-aqmmk4yv-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
  JWT_SECRET = "weight-loss-app-secret-2026"

[[plugins]]
  package = "@netlify/plugin-nextjs"
